"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, FileText, UserRound } from "lucide-react";
import AppShell from "@/app/components/app-shell";

type Patient = { id: number; patientCode: string; fullName: string; dateOfBirth: string; gender: string; phoneCountryCode: string | null; phone: string | null; email: string | null; address: string | null };
type Report = { id: number; reportNumber: string; status: string; reportDate: string | null; tests: { testName: string }[] };
function age(value: string) { const birth = new Date(value); const today = new Date(); let result = today.getFullYear() - birth.getFullYear(); if (today < new Date(today.getFullYear(), birth.getMonth(), birth.getDate())) result--; return result; }
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)) : "Not dated"; }

export default function PatientPage({ params }: { params: Promise<{ id: string }> }) {
  const [patientId, setPatientId] = useState("");
  const [patient, setPatient] = useState<Patient | null>(null);
  const [reports, setReports] = useState<Report[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { params.then(({ id }) => { setPatientId(id); return fetch(`/api/patients/${id}`); }).then((response) => response?.json()).then((data) => { if (!data?.success) throw new Error(data?.error || "Failed to load patient."); setPatient(data.patient); setReports(data.reports); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Failed to load patient.")); }, [params]);
  const testSummary = useMemo(() => (tests: { testName: string }[]) => tests.map((test) => test.testName).join(", "), []);
  return <AppShell title="Patient record"><main className="px-5 py-7 lg:px-8"><div className="mx-auto max-w-[1200px]">{error ? <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</p> : !patient ? <p className="text-slate-500">Loading patient...</p> : <><Link href="/patients" className="mb-5 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-teal-700"><ArrowLeft size={16} /> Patient directory</Link><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-slate-500">Patient record</p><h2 className="mt-1 text-2xl font-semibold">{patient.fullName}</h2><p className="mt-1 text-sm text-slate-500">{patient.patientCode}</p></div><Link href={`/patients/${patientId}/history`} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-semibold text-slate-700"><FileText size={16} /> Report history</Link></div><section className="mt-7 grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-3"><div className="flex items-center gap-3 md:col-span-3"><span className="flex size-10 items-center justify-center rounded-full bg-teal-50 text-teal-700"><UserRound size={19} /></span><div><p className="font-semibold">Patient information</p><p className="text-sm text-slate-500">Demographics and contact details</p></div></div><Info label="Date of birth" value={`${date(patient.dateOfBirth)} (${age(patient.dateOfBirth)} years)`} /><Info label="Gender" value={patient.gender} /><Info label="Phone" value={patient.phone ? `${patient.phoneCountryCode || "+91"} ${patient.phone}` : "-"} /><Info label="Email" value={patient.email || "-"} /><Info label="Address" value={patient.address || "-"} /></section><section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h3 className="font-semibold">Report history</h3><p className="mt-1 text-sm text-slate-500">{reports.length} report{reports.length === 1 ? "" : "s"} on record</p></div>{reports.length === 0 ? <p className="p-8 text-center text-slate-500">No reports found.</p> : <div className="divide-y divide-slate-100">{reports.map((report) => <Link key={report.id} href={`/reports/${report.id}`} className="flex flex-col justify-between gap-2 p-5 hover:bg-slate-50 sm:flex-row sm:items-center"><div><p className="font-semibold text-teal-800">{report.reportNumber}</p><p className="mt-1 text-sm text-slate-500">{testSummary(report.tests) || "No tests"}</p></div><div className="text-left sm:text-right"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{report.status}</span><p className="mt-2 text-xs text-slate-500">{date(report.reportDate)}</p></div></Link>)}</div>}</section></>}</div></main></AppShell>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-medium text-slate-800">{value}</p></div>; }
