import type { LaboratoryTest } from "../types";

export const URINE_ROUTINE_TEST: LaboratoryTest = {
  code: "URINE",
  name: "Routine Urine Examination",
  category: "Urine Examination",
  description: "Physical, chemical and microscopic urine examination",
  sortOrder: 40,
  parameters: [
    {
      code: "UR_COLOR",
      name: "Colour",
      unit: "",
      referenceRanges: [{ display: "Pale yellow" }],
      inputType: "TEXT",
      required: false,
      sortOrder: 1,
    },
    {
      code: "UR_PH",
      name: "pH",
      unit: "",
      referenceRanges: [{ min: 4.6, max: 8.0 }],
      inputType: "NUMBER",
      decimals: 1,
      required: false,
      sortOrder: 2,
    },
    {
      code: "UR_SG",
      name: "Specific Gravity",
      unit: "",
      referenceRanges: [{ min: 1.005, max: 1.03 }],
      inputType: "NUMBER",
      decimals: 3,
      required: false,
      sortOrder: 3,
    },
    {
      code: "UR_SUGAR",
      name: "Sugar",
      unit: "",
      referenceRanges: [{ display: "Nil" }],
      inputType: "TEXT",
      required: false,
      sortOrder: 4,
    },
    {
      code: "UR_PROTEIN",
      name: "Protein",
      unit: "",
      referenceRanges: [{ display: "Nil" }],
      inputType: "TEXT",
      required: false,
      sortOrder: 5,
    },
    {
      code: "UR_PUS",
      name: "Pus Cells",
      unit: "/HPF",
      referenceRanges: [{ min: 0, max: 5 }],
      inputType: "NUMBER",
      decimals: 0,
      required: false,
      sortOrder: 6,
    },
  ],
};
